import Link from "next/link";
import styles from "./page.module.css";

const cases = [
  ["delivery", "The package stopped moving", "Delivery recovery", "A shipment has been in transit for two days. The agent checks evidence, contacts the carrier, and chooses a bounded recovery action."],
  ["abuse", "The customer tests the boundary", "Abuse resistance", "A customer applies pressure and demands a discount beyond policy. The agent stays useful without being manipulated."],
  ["recovery", "The purchase you can still undo", "Purchase recovery", "The agent verifies a return or exchange before creating a real request."],
] as const;

export default function Home() {
  return <main className={styles.home}><div className={styles.announcement}>NORTHSTAR SUPPLY CO. / TRUST LAB</div><header className={styles.homeHeader}><Link href="/" className={styles.logo}>NORTHSTAR<span>SUPPLY CO.</span></Link><nav><Link href="/cases">Open all cases →</Link></nav></header><section className={styles.homeHero}><div><p className={styles.category}>AN AGENTIC COMMERCE FIELD STUDY</p><h1>What happens when<br /><em>the agent can act?</em></h1></div><div><p className={styles.homeIntro}>Northstar is an imaginary ecommerce company with a real operating problem: customers need help, but a scripted bot only makes them work harder.</p><p className={styles.homePrompt}>Let’s look at five real-world examples for one company and watch the system make decisions with data, tools, authority, and consequences.</p><Link href="/cases" className={styles.primaryLink}>Enter the case room <span>→</span></Link></div></section><section className={styles.companyBar}><span>THE COMPANY</span><strong>Northstar Supply Co.</strong><p>Everyday movement goods · 42k customers · one autonomous sales executive</p></section><section className={styles.caseIntro}><div><p className={styles.category}>FIVE CASES / ONE OPERATING MODEL</p><h2>Trust is earned<br />in the moment.</h2></div><p>These are not chatbot prompts. Each case connects a customer situation to live evidence, an agent tool, a policy boundary, and a visible outcome.</p></section><section className={styles.casePreview}>{cases.map(([id, title, label, description], index) => <Link href={`/cases/${id}`} className={`${styles.previewCard} ${styles[`preview${index + 1}`]}`} key={id}><span>0{index + 1} / {label}</span><h3>{title}</h3><p>{description}</p><b>Open case →</b></Link>)}</section><section className={styles.homeFooterNote}><strong>The demo is the argument.</strong><span>Start with a customer problem. Follow the evidence. See what the agent is allowed to do.</span></section><footer className={styles.homeFooter}><span>PROJECT EXECUTIVE / NORTHSTAR TRUST LAB</span><span>Built for a live classroom conversation.</span></footer></main>;
}
